### ISSUE TITLE
API keys exposed

### ISSUE THREAD

**Issue by marcusmoore** [Cgipson06/twitter-client#1]
I was linked from your reddit thread. You shouldn't have your API keys committed in the repo. I don't know much Ruby but check into [dotenv](https://github.com/bkeepers/dotenv) in the future to keep sensitive info secure.

**Comment by Cgipson06** [comment]
Wow thanks so much.  I should have caught that!!  Since that project I have learned to hide the keys in ruby and on heroku, but I dont think I would have found this guy hiding!! 

```
 On Monday, November 9, 2015 5:22 PM, Marcus Moore <notifications@github.com> wrote:
```

 I was linked from your reddit thread. You shouldn't have your API keys committed in the repo. I don't know much Ruby but check into dotenv in the future to keep sensitive info secure.—

**Comment by Cgipson06** [comment]
Taken care of!  Thanks again!
